/**
 * check-brand.mjs: the CI guardrail from @vaguedustin/brand docs/CONSUMING.md.
 *
 * "The single highest-leverage check": fail if a hex literal appears in product source. A colour typed
 * inline is a colour that will not follow the palette when it is retuned upstream, and it is the way
 * every design system quietly rots.
 *
 * Two files are allowed to hold raw values, and both say so in their own header:
 *   src/shared/brand-tokens.ts   the handful the main process needs before any CSS exists
 *   resources/icon-small.svg     a rasterised icon cannot resolve a CSS variable
 *
 * The vendored `styles/brand/*.css` is generated by the brand package and is skipped entirely.
 */

import { readdir, readFile } from 'node:fs/promises';
import { join, relative, resolve, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const SEARCH_ROOTS = ['src', 'resources'];
const EXTENSIONS = new Set(['.ts', '.tsx', '.css', '.html', '.svg']);

/** Paths (relative, POSIX-style) that are permitted to contain raw colour values. */
const ALLOWED = [
  'src/shared/brand-tokens.ts',
  'resources/icon-small.svg',
];

/** Generated or vendored, not product source. */
const SKIPPED_DIRS = ['src/renderer/src/styles/brand'];

const HEX = /#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/g;

/**
 * Colour functions that take literal channel values.
 *
 * `color-mix(in srgb, var(--x) 40%, transparent)` is fine and used everywhere; a bare
 * `rgba(212,175,55,0.4)` is not, because it hard-codes a house colour.
 */
const RAW_FN = /\b(?:rgb|rgba|hsl|hsla)\(\s*[\d.]/g;

async function* walk(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === 'out') continue;
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

const toPosix = (path) => path.split(sep).join('/');

async function main() {
  const problems = [];
  let checked = 0;

  for (const root of SEARCH_ROOTS) {
    for await (const file of walk(join(ROOT, root))) {
      const rel = toPosix(relative(ROOT, file));
      if (!EXTENSIONS.has(file.slice(file.lastIndexOf('.')))) continue;
      if (ALLOWED.includes(rel)) continue;
      if (SKIPPED_DIRS.some((dir) => rel.startsWith(`${dir}/`))) continue;

      checked++;
      const text = await readFile(file, 'utf8');
      const lines = text.split('\n');

      lines.forEach((line, index) => {
        // A hex inside a comment is documentation, not a style declaration.
        const code = line.replace(/\/\/.*$/, '').replace(/\/\*.*?\*\//g, '');

        for (const match of code.matchAll(HEX)) {
          problems.push({ rel, line: index + 1, found: match[0], text: line.trim() });
        }
        for (const match of code.matchAll(RAW_FN)) {
          problems.push({ rel, line: index + 1, found: `${match[0]}…`, text: line.trim() });
        }
      });
    }
  }

  if (problems.length > 0) {
    console.error(`\nRaw colour values found in ${problems.length} place(s):\n`);
    for (const problem of problems) {
      console.error(`  ${problem.rel}:${problem.line}  ${problem.found}`);
      console.error(`    ${problem.text.slice(0, 110)}`);
    }
    console.error(
      '\nUse a semantic token from the vendored brand CSS instead, e.g. var(--accent-default),',
    );
    console.error('or color-mix(in srgb, var(--status-warning) 30%, transparent).\n');
    process.exitCode = 1;
    return;
  }

  console.log(`brand check passed, no raw colour values in ${checked} product source file(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
